<h1>Welcomme to Hotel California Bitch!</h1>
<form action="<?= route_to_url('default') ?>" method="post">
    <input type="checkbox" name="hasAirConditioner" value="True">Air Conditionné
    <input type="submit">
</form>

<table class="table table-hover">
    <thead>
    <tr>
        <th>Chambre</th>
        <?php for($day = 0; $day < $calendar['dayCount']; $day++): ?>
            <th><?= $calendar['firstDay'] + $day ?></th>
        <?php endfor; ?>
    </tr>
    </thead>
    <tbody>
        <?php foreach($rooms as $room): ?>
            <tr>
                <td><?= $room['number'] ?></td>
	            <?php for($day = 0; $day < $calendar['dayCount']; $day++): ?>
	             <?php if ($room['occupancy'][$day]['status'] == 'booked') : ?>
                    <td> X </td>
	              <?php else: ?>
                    <td></td>
                <?php endif; ?>
	               <?php endfor; ?>
            </tr>
        <?php endforeach; ?>

    </tbody>
</table>